name: CI

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 21
      - name: clean build
        run: ./gradlew clean test --info --stacktrace